import { StyleSheet } from "react-native";
const blue = "#6264ff";
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#090911" },
  shade: { flex: 1, backgroundColor: "rgba(6,6,13,.83)" },
  control: {
    width: 36,
    height: 36,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  project: {
    height: 62,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#33313d",
  },
  avatar: { width: 28, height: 28, resizeMode: "contain" },
  projectName: { flex: 1, color: "#f1f1f7", fontSize: 20, fontWeight: "600" },
  count: { color: "#9898a5", fontSize: 15 },
  thread: {
    paddingVertical: 11,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#33313d",
    backgroundColor: "rgba(23,22,37,.3)",
    gap: 5,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 5 },
  modelLogo: { width: 16, height: 13, resizeMode: "contain" },
  model: { fontSize: 12, color: "#9494a4" },
  time: { fontSize: 12, color: "#70707e" },
  badge: {
    fontSize: 11,
    color: "#8587ff",
    backgroundColor: "#25264a",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  threadTitle: { fontSize: 16, color: "#f5f5fa", letterSpacing: -0.2 },
  branch: { fontSize: 12, color: "#737381", flex: 1 },
  newSession: {
    height: 54,
    borderRadius: 17,
    backgroundColor: "#202024",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    gap: 12,
  },
  newLabel: { color: "#f5f5fa", fontSize: 17, fontWeight: "500" },
  composer: { padding: 20, minHeight: 350 },
  composerTitle: { color: "#f7f7fc", fontSize: 22, fontWeight: "600" },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    padding: 10,
    borderRadius: 9,
    backgroundColor: "#222229",
    borderWidth: 1,
    borderColor: "transparent",
  },
  selected: { borderColor: blue, backgroundColor: "#252544" },
  checkout: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#35353e",
    paddingVertical: 12,
  },
  prompt: {
    color: "#f5f5fa",
    fontSize: 20,
    paddingTop: 22,
    minHeight: 82,
    maxHeight: 150,
    textAlignVertical: "top",
  },
  hint: { fontSize: 13, color: "#656574" },
  send: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: blue,
    alignItems: "center",
    justifyContent: "center",
  },
  detail: { padding: 24, gap: 18 },
  eyebrow: { fontSize: 12, color: "#8b8b9d", lineHeight: 18 },
  detailTitle: {
    color: "#f7f7fc",
    fontSize: 27,
    fontWeight: "600",
    letterSpacing: -0.6,
  },
  body: { color: "#d2d2df", fontSize: 14, lineHeight: 22 },
  message: {
    backgroundColor: "rgba(31,31,43,.85)",
    padding: 18,
    borderRadius: 16,
    gap: 12,
  },
  outlineButton: {
    borderColor: "#454552",
    borderWidth: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  search: {
    margin: 20,
    padding: 14,
    backgroundColor: "#22222c",
    color: "white",
    borderRadius: 12,
    fontSize: 16,
  },
  empty: { padding: 24, color: "#aaaabb" },
  note: {
    backgroundColor: "#1b1b26",
    borderRadius: 12,
    padding: 16,
    minHeight: 220,
    color: "#f4f4ff",
    textAlignVertical: "top",
    fontSize: 16,
  },
});
